### ISSUE TITLE
How to add a photo on Awesome-CV?

### ISSUE THREAD

**Issue by miklovv** [posquit0/Awesome-CV#270]
Hi all, 
Please, could you give me any suggestions to add a photo (next to Personal information) in my cv? Not able to do that by modifying awesome-cv.cls file...

Thanks in advance,
miklovv

**Comment by IlyaKisil** [comment]
In order to add photo, you don't need to modify `awesome-cv.cls`. It provides you with such command. Instead, you need to use (uncomment) in it your `cv.tex` file under the **PERSONAL INFORMATION** section in the preamble. By default, this command will put photo on the left side, will cropped it into a circle shape and add border around it:
```
\photo{./my_photo.png}
```

<img width="1318" alt="screen shot 2019-03-03 at 01 22 09" src="https://user-images.githubusercontent.com/16823400/53689694-47eff980-3d53-11e9-94a6-a8d3718c71fd.png">

**Note**, that here you need to specify path to png file with respect to the main `awesome-cv.cls` file  and not its symbolic link.

You can also specify optional arguments in order to change default settings:
```
% Photo will be placed on the right side
\photo[right]{./my_photo.png}

% No edge around the photo
\photo[noedge]{./my_photo.png}

% Photo won't be cropped and will be as a rectangle
\photo[rectangle]{./my_photo.png}
```

You can combined these options, if you want to use some of them at the same time (order doesn't matter)
```
\photo[right,rectangle]{./my_photo.png}
```

<img width="1305" alt="screen shot 2019-03-03 at 01 24 11" src="https://user-images.githubusercontent.com/16823400/53689691-3dcdfb00-3d53-11e9-820b-df904e89f53f.png">

**Comment by miklovv** [comment]
Thanks Ilya, really appreciated your answer!!
