### ISSUE TITLE
tilde in url is disappeared

### ISSUE THREAD

**Issue by Doowon** [posquit0/Awesome-CV#35]
If a url in the "\homepage{}" has a tilde, the tilde is disappeared.

**Comment by posquit0** [comment]
It's not problem of Awesome CV
Try to read [http://tex.stackexchange.com/questions/9363/how-does-one-insert-a-backslash-or-a-tilde-into-latex](this thread)

**Comment by rkillick** [comment]
This doesn't solve this problem.  If you put $\sim$ then the URL doesn't work properly.  If you put \~{}
 then again the link doesn't work.  It would be solved by encasing the URL in \url{} but this breaks the build - because you are using \href in the .cls definition.  The problem is that \url treats URLs properly whereas \href doesn't.  Can you not just use \url in the .cls definition?
This would require two parts, the first being the favicon using \href and the second part using \url.

**Comment by jorge-castro** [comment]
While this issue has been closed I still stumbled upon this problem. I was able to fix it by using `\string~` when inputting the URL. For instance:

`\homepage{git.sr.ht/\string~jorgecastro}`
