### ISSUE TITLE
Two lines instead of one - fill blank space in cventry

### ISSUE THREAD

**Issue by StevenSalazarM** [posquit0/Awesome-CV#350]
Hello, since the last 5 days I have been trying to understand how to modify the alignments of cventry but I had no success. I would be really grateful if someone know how to solve this:

![Screenshot_111](https://user-images.githubusercontent.com/22026947/99118361-adebe580-25f7-11eb-937a-8df7462c14f3.png)

I would like to have 'Details' in the same line of [certificate] since there is enough space for it.

**Comment by eosti** [comment]
In `awesome-cv.cls`, go to the `\cventry` definition (line 602-ish), and look at this line:

`\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} L{\textwidth - 4.5cm} R{4.5cm}}`

To make the title wider, reduce the first 4.5cm value, and to make sure that the title won't collide with the location and dates, adjust the second 4.5cm value to match the first. Note that this will change _every_ cventry to have these widths, so if this will cause problems you may want to just manually create the tabular environment for that one entry within the subfile instead of using the `\cventry` macro.

**Comment by StevenSalazarM** [comment]
> 
> 
> In `awesome-cv.cls`, go to the `\cventry` definition (line 602-ish), and look at this line:
> 
> `\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} L{\textwidth - 4.5cm} R{4.5cm}}`
> 
> To make the title wider, reduce the first 4.5cm value, and to make sure that the title won't collide with the location and dates, adjust the second 4.5cm value to match the first. Note that this will change _every_ cventry to have these widths, so if this will cause problems you may want to just manually create the tabular environment for that one entry within the subfile instead of using the `\cventry` macro.

Yes, it worked (4cm was the right value for me). Thank you!
